export const links = {
  email: 'mailto:yixinchen0320@gmail.com',
  pku: 'mailto:2311110791@stu.pku.edu.cn',
  scholar: 'https://scholar.google.com/citations?hl=en&user=ymfVoFwAAAAJ',
  github: 'https://github.com/YixinChen-AI',
  orcid: 'https://orcid.org/0000-0002-2727-6387',
  mpum: 'https://www.nature.com/articles/s41467-025-64469-w',
  mpumCode: 'https://github.com/YixinChen-AI/MPUM',
  autopet: 'https://github.com/YixinChen-AI/autopet-v',
  pcnet: 'https://doi.org/10.1109/TMI.2024.3395349',
  fvp: 'https://doi.org/10.1109/TMI.2023.3306105',
  lucida: 'https://doi.org/10.1007/978-3-031-72111-3_37',
  lucidaCode: 'https://github.com/YixinChen-AI/LUCIDA',
  trpms: 'https://doi.org/10.1109/TRPMS.2024.3391285',
  trpmsCode: 'https://github.com/YixinChen-AI/BraSEDA',
  hds: 'https://doi.org/10.34133/hds.0143',
  regPaper: 'https://papers.miccai.org/miccai-2026-sat/REG2026_008.html',
  cmrPaper: 'https://papers.miccai.org/miccai-2026-sat/CMRSeg_018.html',
  mvaaPaper: 'https://papers.miccai.org/miccai-2026-sat/MVAA_023.html',
  course: 'https://www.tech-skills.org.cn/lesson/811',
  cv: 'output/pdf/Yixin-Chen-CV.pdf',
};

export const shared = {
  awardImage: 'assets/img/autopet-award-2026.jpeg',
  regPosterImage: 'assets/img/reg2-poster-2026.jpg',
  mvaaPosterImage: 'assets/img/mvaa-poster-2026.jpg',
  portraitImage: 'assets/img/avatar.png',
  bookImage: 'assets/img/book.png',
  years: ['2026', '2025', '2024', '2023', '2022', '2021', '2020', '2019'],
};

export const en = {
  lang: 'en', name: 'Yixin Chen', otherName: '陈亦新',
  title: 'Yixin Chen | Peking University',
  description: 'Yixin Chen, PhD candidate at Peking University. Research in medical image segmentation, cross-modality learning, and clinical imaging of cancer and metabolic disease.',
  nav: ['Timeline', 'Research', 'Publications', 'Contact'], skip: 'Skip to content',
  affiliation: 'PhD candidate, Peking University',
  intro: 'I work on medical image segmentation and learning across PET, CT and MRI. My clinical research focuses on cancer, fatty liver disease and multi-organ metabolism.',
  scholar: 'Google Scholar', email: 'Email', cv: 'CV',
  portraitAlt: 'Portrait of Yixin Chen', portraitCaption: 'Yixin Chen',
  journey: 'Timeline', yearNav: 'Browse by year',
  latestLabel: 'MICCAI 2026 challenges',
  awardTitle: 'autoPET V: second place in Category 1',
  awardBody: 'Our team, CYX-AI, developed an interactive PET/CT lesion segmentation method that combines neural-network corrections with local threshold updates.',
  awardLink: 'Method and code',
  awardAlt: 'CYX-AI receiving the autoPET V Category 1 second-place award at MICCAI 2026',
  awardCaption: 'autoPET V award presentation, MICCAI 2026',
  fullPhoto: 'View full photo',
  awards: [
    {title:'CMR-MULTI: second place', detail:'Multi-sequence cardiac MRI segmentation. Method paper selected for a CMRSeg challenge oral presentation.', href:links.cmrPaper, link:'Method paper'},
    {title:'REG²: fourth place', detail:'Method paper selected for a MICCAI 2026 challenge workshop poster.', href:links.regPaper, link:'Method paper'},
  ],
  workshop: {title:'MVAA 2026: poster', detail:'Mitral-valve segmentation across cardiac CT, 3D ultrasound and surgical video.', href:links.mvaaPaper, link:'Method paper'},
  posterPhotos: [
    {image:shared.regPosterImage, caption:'REG² poster at MICCAI 2026', alt:'Yixin Chen standing beside his REG² pathology-workflow poster'},
    {image:shared.mvaaPosterImage, caption:'MVAA poster at MICCAI 2026', alt:'Yixin Chen standing beside his MVAA mitral-valve segmentation poster'},
  ],
  clinicalTitle: 'Multi-organ metabolism in MASLD',
  clinicalBody: 'Co-first-author study accepted in EJNMMI.',
  fundingDate: '2026–2027, NSFC grant for doctoral students',
  fundingTitle: 'NSFC doctoral research project',
  fundingBody: 'Principal investigator of a project on extracting and analysing multi-organ metabolic information from total-body PET/CT.',
  papers2026: [
    {title:'NeuronCtrl', body:'Second author. Studies safe control of changes in neuronal microenvironments.', venue:'ICML 2026 Spotlight', href:'#publication-neuronctrl'},
    {title:'PHATE-Net', body:'First author. Uses PET images to study disease trajectories.', venue:'CVPR 2026 Findings', href:'#publication-phate'},
  ],
  mpumTitle: 'MPUM: segmentation across CT, MRI and PET',
  mpumBody: 'Co-first-author paper published in Nature Communications on 24 October.',
  paperLink: 'Paper', codeLink: 'Code',
  papers2024: [
    {title:'PCNet', body:'First-author paper on anatomy-guided universal CT segmentation.', venue:'IEEE TMI', href:links.pcnet},
    {title:'LUCIDA', body:'First-author paper and MICCAI 2024 poster. Image reconstruction guides adaptation to low-dose CT without low-dose segmentation labels.', venue:'MICCAI', href:links.lucida, code:links.lucidaCode},
    {title:'CT whole-brain segmentation', body:'Co-first-author study using anatomical structure to guide unsupervised domain adaptation.', venue:'IEEE TRPMS', href:links.trpms, code:links.trpmsCode},
  ],
  paper2025: {title:'VP-SFDA', body:'First-author paper on visual prompting for cross-modality medical segmentation, using a pretrained model without access to its original training data.', venue:'Health Data Science', href:links.hds},
  paper2023: {title:'FVP', body:'Fourier visual prompting for medical segmentation domain adaptation.', venue:'IEEE TMI', href:links.fvp},
  phdTitle: 'PhD in Medical Technology, Peking University',
  phdDate: 'September 2023–present',
  jobs: [
    {
      name:'AirDoc', role:'Algorithm Engineer', date:'July–September 2022',
      paragraphs: [
        'Developed a model to predict the gap between an implanted ICL lens and the natural lens after surgery, using eye measurements and lens size.',
        'Worked on ultra-widefield fundus image analysis, clinical requirements and medical-device registration.',
      ],
    },
    {
      name:'BioMind', role:'Medical Imaging Algorithm Engineer', date:'November 2020–June 2022',
      paragraphs: [
        'Developed cardiac ultrasound models for image quality assessment, Doppler segmentation and measurement, septal defect detection and valve regurgitation analysis.',
        'Worked with clinicians to integrate models into an ultrasound-assisted diagnosis system. Also contributed to an ovarian-tumour ultrasound system.',
      ],
    },
  ],
  bookWritingTitle: 'Writing my first deep-learning book',
  bookWritingBody: 'Wrote the manuscript during my studies in London, covering machine-learning methods and PyTorch examples.',
  bookWritingDate: 'January–October 2020',
  bookName: 'Deep Learning Theory and Practice: PyTorch Case Studies',
  bookDetail: 'Sole author. Published by Tsinghua University Press in 2021.',
  bookAlt: 'Cover of Deep Learning: Theory and Practice, published by Tsinghua University Press',
  londonTitle: 'King’s College London',
  londonDegree: 'MSc in Artificial Intelligence, with Distinction',
  londonDate: '2019–2020',
  londonBody: 'Began studying AI in London in September 2019, with coursework in computer vision, data mining and pattern recognition.',
  undergraduate: 'Xiamen University, 2015–2019. BSc in Automation and a second bachelor’s degree in Mathematical Finance.',
  publications: 'Publications', allPapers: 'Google Scholar',
  service: 'Teaching, patents and reviewing',
  patentTitle: '12 invention patents',
  patentDetail: '4 granted; 8 under substantive examination.',
  reviewTitle: 'Nature Communications', reviewDetail: 'Early Career Co-Reviewer',
  teachingTitle: 'Computer-vision teaching',
  teachingDetail: 'Recorded introductory and intermediate courses on machine learning and computer vision.',
  teachingLink: 'View introductory course',
  writingTitle: '“机器学习炼丹术” on WeChat',
  writingDetail: 'Shared notes on machine-learning practice and medical imaging through my technical WeChat account.',
  contactTitle: 'Contact', pkuEmail: 'Peking University',
  footer: 'Yixin Chen', updated: 'Updated September 2026',
};

export const zh = {
  lang: 'zh-CN', name: '陈亦新', otherName: 'Yixin Chen',
  title: '陈亦新 | 北京大学',
  description: '陈亦新，北京大学博士研究生。研究医学影像分割、跨模态学习，以及肿瘤、脂肪肝和多器官代谢的临床影像分析。',
  nav: ['时间线', '研究', '论文', '联系'], skip: '跳转到正文',
  affiliation: '北京大学博士研究生',
  intro: '我研究医学影像分割与 PET、CT、MRI 之间的跨模态学习，也开展肿瘤、脂肪肝和多器官代谢的临床影像研究。',
  scholar: 'Google Scholar', email: '邮箱', cv: '英文 CV',
  portraitAlt: '陈亦新的个人照', portraitCaption: '陈亦新',
  journey: '时间线', yearNav: '按年份浏览',
  latestLabel: 'MICCAI 2026 挑战赛',
  awardTitle: 'autoPET V：Category 1 第二名',
  awardBody: 'CYX-AI 团队将神经网络修正与局部阈值调整结合，用于交互式 PET/CT 病灶分割。',
  awardLink: '方法与代码',
  awardAlt: 'CYX-AI 在 MICCAI 2026 获得 autoPET V Category 1 第二名的颁奖合影',
  awardCaption: 'MICCAI 2026，autoPET V 颁奖现场',
  fullPhoto: '查看完整照片',
  awards: [
    {title:'CMR-MULTI：第二名', detail:'多序列心脏 MRI 分割，方法论文入选 CMRSeg 挑战赛口头报告。', href:links.cmrPaper, link:'方法论文'},
    {title:'REG²：第四名', detail:'方法论文入选 MICCAI 2026 挑战赛 workshop 海报。', href:links.regPaper, link:'方法论文'},
  ],
  workshop: {title:'MVAA 2026：海报报告', detail:'研究心脏 CT、三维超声和手术视频中的二尖瓣分割。', href:links.mvaaPaper, link:'方法论文'},
  posterPhotos: [
    {image:shared.regPosterImage, caption:'MICCAI 2026，REG² 海报现场', alt:'陈亦新在 REG² 病理流程研究海报前的合影'},
    {image:shared.mvaaPosterImage, caption:'MICCAI 2026，MVAA 海报现场', alt:'陈亦新在 MVAA 二尖瓣分割研究海报前的合影'},
  ],
  clinicalTitle: 'MASLD 的多器官代谢研究',
  clinicalBody: '共同第一作者研究被 EJNMMI 接收。',
  fundingDate: '2026–2027，青年学生基础研究项目（博士研究生）',
  fundingTitle: '国家自然科学基金博士生项目',
  fundingBody: '项目负责人，研究全人体 PET/CT 的多器官代谢信息提取与分析。',
  papers2026: [
    {title:'NeuronCtrl', body:'第二作者，研究神经元微环境变化的安全控制。', venue:'ICML 2026 Spotlight', href:'#publication-neuronctrl'},
    {title:'PHATE-Net', body:'第一作者，利用 PET 影像研究疾病变化轨迹。', venue:'CVPR 2026 Findings', href:'#publication-phate'},
  ],
  mpumTitle: 'MPUM：CT、MRI 与 PET 通用分割',
  mpumBody: '共同第一作者论文，10 月 24 日发表于 Nature Communications。',
  paperLink: '论文', codeLink: '代码',
  papers2024: [
    {title:'PCNet', body:'第一作者论文，用解剖先验指导 CT 通用分割。', venue:'IEEE TMI', href:links.pcnet},
    {title:'LUCIDA', body:'第一作者论文，MICCAI 2024 海报。利用图像重建指导低剂量 CT 的域适应，无需低剂量分割标注。', venue:'MICCAI', href:links.lucida, code:links.lucidaCode},
    {title:'CT 全脑分割', body:'共同第一作者研究，利用解剖结构指导无监督域适应。', venue:'IEEE TRPMS', href:links.trpms, code:links.trpmsCode},
  ],
  paper2025: {title:'VP-SFDA', body:'第一作者论文，利用视觉提示进行跨模态分割适应，使用预训练模型，无需访问其原始训练数据。', venue:'Health Data Science', href:links.hds},
  paper2023: {title:'FVP', body:'利用傅里叶视觉提示进行医学影像分割域适应。', venue:'IEEE TMI', href:links.fvp},
  phdTitle: '北京大学，医学技术博士',
  phdDate: '2023 年 9 月至今',
  jobs: [
    {
      name:'鹰瞳科技 AirDoc', role:'注册算法工程师', date:'2022 年 7 月–9 月',
      paragraphs: [
        '研发 ICL 术后拱高预测模型，利用眼部测量与晶体尺寸，预测手术后植入晶体与自身晶状体之间的距离。',
        '开展超广角眼底图像分析、临床需求调研，并参与医疗器械注册工作。',
      ],
    },
    {
      name:'安德医智 BioMind', role:'医疗图像深度学习算法工程师', date:'2020 年 11 月–2022 年 6 月',
      paragraphs: [
        '开发心脏超声模型，负责图像质控、多普勒频谱分割与测量、间隔缺损检测及瓣膜反流分析。',
        '与医生梳理诊断流程，将模型接入超声辅助诊断系统，并参与卵巢肿块智能诊疗系统研发。',
      ],
    },
  ],
  bookWritingTitle: '撰写第一本深度学习书籍',
  bookWritingBody: '在伦敦求学期间撰写书稿，整理机器学习方法与 PyTorch 示例。',
  bookWritingDate: '2020 年 1–10 月',
  bookName: '《深度学习理论与实战：PyTorch 案例详解》',
  bookDetail: '独著，清华大学出版社，2021 年。',
  bookAlt: '《深度学习理论与实战：PyTorch 案例详解》书封',
  londonTitle: '伦敦国王学院',
  londonDegree: '人工智能硕士，Distinction',
  londonDate: '2019–2020 年',
  londonBody: '2019 年 9 月在伦敦开始学习人工智能，修读计算机视觉、数据挖掘与模式识别课程。',
  undergraduate: '2015–2019 年，厦门大学自动化本科，同时取得数理金融第二学位。',
  publications: '论文', allPapers: 'Google Scholar',
  service: '教学、专利与审稿',
  patentTitle: '12 项发明专利',
  patentDetail: '4 项已授权，8 项实质审查中。',
  reviewTitle: 'Nature Communications', reviewDetail: 'Early Career Co-Reviewer，合作审稿',
  teachingTitle: '计算机视觉课程讲师',
  teachingDetail: '录制初级与中级课程，讲解机器学习基础及视觉算法。',
  teachingLink: '查看初级课程',
  writingTitle: '机器学习炼丹术',
  writingDetail: '通过公众号分享机器学习实践与医学影像笔记。',
  contactTitle: '联系', pkuEmail: '北京大学',
  footer: '陈亦新', updated: '更新于 2026 年 9 月',
};
