export const links = {
  email: 'mailto:yixinchen0320@gmail.com',
  pku: 'mailto:2311110791@stu.pku.edu.cn',
  scholar: 'https://scholar.google.com/citations?hl=en&user=ymfVoFwAAAAJ',
  github: 'https://github.com/YixinChen-AI',
  orcid: 'https://orcid.org/0000-0002-2727-6387',
  mpum: 'https://www.nature.com/articles/s41467-025-64469-w',
  mpumCode: 'https://github.com/YixinChen-AI/MPUM',
  autopet: 'https://github.com/YixinChen-AI/autopet-v',
  pcnet: 'https://doi.org/10.1109/TMI.2024.3395349',
  fvp: 'https://doi.org/10.1109/TMI.2023.3306105',
  lucida: 'https://doi.org/10.1007/978-3-031-72111-3_37',
  reg: 'https://reg2026.grand-challenge.org/evaluation/test-phase-1/leaderboard/',
  cmr: 'https://mwm2026.github.io/',
};

export const shared = {
  awardImage: 'assets/img/autopet-award-2026.jpeg',
  portraitImage: 'assets/img/avatar.png',
  bookImage: 'assets/img/book.png',
  years: ['2026', '2025', '2024', '2023', '2022', '2021', '2020', '2019'],
};

export const en = {
  lang: 'en', name: 'Yixin Chen', otherName: '陈亦新',
  title: 'Yixin Chen | Peking University',
  description: 'Yixin Chen, PhD candidate at Peking University. Research in medical image segmentation, cross-modality learning, and clinical imaging of cancer and metabolic disease.',
  nav: ['Timeline', 'Publications', 'Contact'], skip: 'Skip to content',
  affiliation: 'PhD candidate, Peking University',
  intro: 'I work on medical image segmentation and learning across PET, CT and MRI. My clinical research focuses on cancer, fatty liver disease and multi-organ metabolism.',
  scholar: 'Google Scholar', email: 'Email',
  portraitAlt: 'Portrait of Yixin Chen', portraitCaption: 'Yixin Chen',
  journey: 'Research, work and education', yearNav: 'Browse by year',
  latestLabel: 'September 2026, MICCAI',
  awardTitle: 'autoPET V: second place in Category 1',
  awardBody: 'Our team, CYX-AI, developed an interactive PET/CT lesion segmentation method that combines neural-network corrections with local threshold updates.',
  awardLink: 'Method and code',
  awardAlt: 'CYX-AI receiving the autoPET V Category 1 second-place award at MICCAI 2026',
  awardCaption: 'autoPET V award presentation, MICCAI 2026',
  fullPhoto: 'View full photo',
  awards: [
    {title:'CMR-MULTI: second place', detail:'Multi-sequence cardiac MRI segmentation. Method paper accepted for an oral presentation at CMRSeg.', href:links.cmr, link:'CMRSeg workshop'},
    {title:'REG²: Top-ranked team', detail:'Confirmed by the organizers; third in public Test Phase 1. Method paper accepted as a workshop poster.', href:links.reg, link:'Test Phase 1 leaderboard'},
  ],
  clinicalTitle: 'Multi-organ metabolism in MASLD',
  clinicalStatus: 'EJNMMI, accepted',
  clinicalBody: 'We used whole-body PET/CT to study metabolic changes across organs in metabolic dysfunction-associated steatotic liver disease (MASLD).',
  fundingDate: 'January 2026',
  fundingTitle: 'NSFC doctoral research project',
  fundingBody: 'I lead a two-year project on total-body PET/CT metabolic analysis, funded by the National Natural Science Foundation of China.',
  mpumTitle: 'MPUM: segmentation across CT, MRI and PET',
  mpumBody: 'A modality-projection model for segmenting 215 anatomical structures across three imaging modalities.',
  paperLink: 'Paper', codeLink: 'Code',
  papers2024: [
    {title:'PCNet', body:'Organ-category priors for universal CT segmentation.', venue:'IEEE TMI', href:links.pcnet},
    {title:'LUCIDA', body:'Domain adaptation for low-dose CT segmentation.', venue:'MICCAI', href:links.lucida},
  ],
  paper2023: {title:'FVP', body:'Fourier visual prompting for medical segmentation domain adaptation.', venue:'IEEE TMI', href:links.fvp},
  phdTitle: 'PhD in Medical Technology, Peking University',
  phdDate: 'September 2023–present',
  jobs: [
    {name:'AirDoc', role:'Researcher, Machine Learning', date:'July–September 2022'},
    {name:'BioMind', role:'Researcher, Machine Learning', date:'November 2020–June 2022'},
  ],
  bookName: 'Deep Learning: Theory and Practice — PyTorch Case Studies',
  bookDetail: 'Sole author. Published by Tsinghua University Press in 2021.',
  bookAlt: 'Cover of Deep Learning: Theory and Practice, published by Tsinghua University Press',
  londonTitle: 'King’s College London',
  londonDegree: 'MSc in Informatics, with Distinction',
  londonDate: 'September 2019–September 2020',
  londonBody: 'During my studies in the UK, I began learning AI and writing my first book on deep learning.',
  undergraduate: 'BSc in Automation, Xiamen University, 2015–2019.',
  publications: 'Selected publications', allPapers: 'Google Scholar',
  service: 'Patents and reviewing',
  patentTitle: '12 invention patents',
  patentDetail: '4 granted; 8 under substantive examination.',
  reviewTitle: 'Nature Communications', reviewDetail: 'Reviewer',
  contactTitle: 'Contact', pkuEmail: 'Peking University',
  footer: 'Yixin Chen', updated: 'Updated September 2026',
};

export const zh = {
  lang: 'zh-CN', name: '陈亦新', otherName: 'Yixin Chen',
  title: '陈亦新 | 北京大学',
  description: '陈亦新，北京大学博士研究生。研究医学影像分割、跨模态学习，以及肿瘤、脂肪肝和多器官代谢的临床影像分析。',
  nav: ['时间线', '论文', '联系'], skip: '跳转到正文',
  affiliation: '北京大学博士研究生',
  intro: '我研究医学影像分割与 PET、CT、MRI 之间的跨模态学习，也开展肿瘤、脂肪肝和多器官代谢的临床影像研究。',
  scholar: 'Google Scholar', email: '邮箱',
  portraitAlt: '陈亦新的个人照', portraitCaption: '陈亦新',
  journey: '研究、工作与教育', yearNav: '按年份浏览',
  latestLabel: '2026 年 9 月，MICCAI',
  awardTitle: 'autoPET V：Category 1 第二名',
  awardBody: 'CYX-AI 团队将神经网络修正与局部阈值调整结合，用于交互式 PET/CT 病灶分割。',
  awardLink: '方法与代码',
  awardAlt: 'CYX-AI 在 MICCAI 2026 获得 autoPET V Category 1 第二名的颁奖合影',
  awardCaption: 'MICCAI 2026，autoPET V 颁奖现场',
  fullPhoto: '查看完整照片',
  awards: [
    {title:'CMR-MULTI：第二名', detail:'多序列心脏 MRI 分割，方法论文被 CMRSeg workshop 接收为口头报告。', href:links.cmr, link:'CMRSeg workshop'},
    {title:'REG²：Top-ranked team', detail:'主办方邮件确认；公开第一阶段排名第 3，方法论文被接收为 workshop 海报。', href:links.reg, link:'第一阶段榜单'},
  ],
  clinicalTitle: 'MASLD 的多器官代谢研究',
  clinicalStatus: 'EJNMMI，已接收',
  clinicalBody: '利用全身 PET/CT 研究代谢功能障碍相关脂肪性肝病（MASLD）的多器官代谢变化。',
  fundingDate: '2026 年 1 月',
  fundingTitle: '国家自然科学基金博士生项目',
  fundingBody: '主持两年期项目，研究全身 PET/CT 的多器官代谢分析。',
  mpumTitle: 'MPUM：CT、MRI 与 PET 通用分割',
  mpumBody: '通过模态投影，在三种影像模态中分割 215 个解剖结构。',
  paperLink: '论文', codeLink: '代码',
  papers2024: [
    {title:'PCNet', body:'利用器官类别先验进行 CT 通用分割。', venue:'IEEE TMI', href:links.pcnet},
    {title:'LUCIDA', body:'面向低剂量 CT 分割的域适应。', venue:'MICCAI', href:links.lucida},
  ],
  paper2023: {title:'FVP', body:'利用傅里叶视觉提示进行医学影像分割域适应。', venue:'IEEE TMI', href:links.fvp},
  phdTitle: '北京大学，医学技术博士',
  phdDate: '2023 年 9 月至今',
  jobs: [
    {name:'鹰瞳科技 AirDoc', role:'机器学习研究员', date:'2022 年 7 月–9 月'},
    {name:'BioMind', role:'机器学习研究员', date:'2020 年 11 月–2022 年 6 月'},
  ],
  bookName: '《深度学习：理论与实战，PyTorch 案例详解》',
  bookDetail: '独著，清华大学出版社，2021 年。',
  bookAlt: '《深度学习：理论与实战，PyTorch 案例详解》书封',
  londonTitle: '伦敦国王学院',
  londonDegree: '信息学硕士，Distinction',
  londonDate: '2019 年 9 月–2020 年 9 月',
  londonBody: '在英国求学期间开始学习人工智能，并着手撰写第一本深度学习书籍。',
  undergraduate: '2015–2019 年，厦门大学自动化专业本科。',
  publications: '代表论文', allPapers: 'Google Scholar',
  service: '专利与审稿',
  patentTitle: '12 项发明专利',
  patentDetail: '4 项已授权，8 项实质审查中。',
  reviewTitle: 'Nature Communications', reviewDetail: '审稿人',
  contactTitle: '联系', pkuEmail: '北京大学',
  footer: '陈亦新', updated: '更新于 2026 年 9 月',
};
