export const research = {
  en: {
    heading: 'Selected research',
    figureLink: 'View full figure',
    works: [
      {
        id: 'mpum',
        title: 'MPUM: one segmentation model for CT, MRI and PET',
        name: 'MPUM',
        venue: 'Nature Communications, 2025',
        summary: 'It shares anatomical knowledge across modalities while adapting to each one, and achieved the highest Dice scores among the compared methods on the evaluated benchmarks.',
        links: [
          { label: 'Paper', href: 'https://www.nature.com/articles/s41467-025-64469-w' },
          { label: 'Code', href: 'https://github.com/YixinChen-AI/MPUM' },
        ],
        image: 'assets/img/research/mpum-overview.png',
        width: 2000, height: 1811,
        alt: 'MPUM overview showing modality-specific kernels, anatomical segmentation and clinical analyses',
        previewAlt: 'MR, PET and CT images with their corresponding MPUM segmentation outputs',
        fullCaption: 'MPUM framework and clinical studies, Figure 1.',
        credit: { label: 'Chen et al., Nature Communications', href: 'https://www.nature.com/articles/s41467-025-64469-w' },
        license: { label: 'CC BY-NC-ND 4.0', href: 'https://creativecommons.org/licenses/by-nc-nd/4.0/' },
      },
      {
        id: 'pcnet',
        title: 'PCNet: anatomical relationships for CT segmentation',
        name: 'PCNet',
        venue: 'IEEE TMI, 2024',
        summary: 'It uses relationships between organs, bones and muscles to guide CT segmentation, improving performance in the paper’s experiments.',
        links: [
          { label: 'Paper', href: 'https://doi.org/10.1109/TMI.2024.3395349' },
          { label: 'Code', href: 'https://github.com/YixinChen-AI/PCNet' },
        ],
        image: 'assets/img/research/pcnet-hierarchy.png',
        width: 1788, height: 998, dark: true,
        alt: 'PCNet anatomical hierarchy linking functional systems with organs, vessels, muscles and bones',
        previewAlt: 'Central part of the PCNet anatomical hierarchy showing relationships among organs, vessels, muscles and bones',
        fullCaption: 'The anatomical hierarchy used in PCNet.',
        credit: { label: 'Original diagram from the PCNet repository', href: 'https://github.com/YixinChen-AI/PCNet' },
      },
      {
        id: 'masld',
        title: 'Multi-organ PET/CT findings in fatty liver disease',
        name: 'Whole-body PET/CT in MASLD',
        venue: 'EJNMMI, accepted 2026',
        summary: 'In 294 adults at two centres, 16 imaging features differed between MASLD and controls and were replicated at the second centre.',
        links: [
          { label: 'Publication entry', href: '#publication-masld' },
        ],
        image: 'assets/img/research/masld-petct.png',
        width: 1753, height: 1253,
        alt: 'MASLD study figure showing PET/CT examples, multi-organ segmentation and organ-level measurements',
        previewAlt: 'Detail of MASLD Figure 2 showing whole-body segmentation and organ groups',
        fullCaption: 'PET/CT and multi-organ segmentation, Figure 2 of the accepted manuscript.',
        credit: { label: 'Chen, Zhou, Guo et al.' },
      },
    ],
  },
  zh: {
    heading: '代表研究',
    figureLink: '查看完整原图',
    works: [
      {
        id: 'mpum',
        title: 'MPUM：一个模型分割 CT、MRI 与 PET',
        name: 'MPUM',
        venue: 'Nature Communications，2025',
        summary: '模型共享不同影像模态的解剖知识，同时适应各模态；在论文评估的任务中，Dice 评分高于所比较的方法。',
        links: [
          { label: '论文', href: 'https://www.nature.com/articles/s41467-025-64469-w' },
          { label: '代码', href: 'https://github.com/YixinChen-AI/MPUM' },
        ],
        image: 'assets/img/research/mpum-overview.png',
        width: 2000, height: 1811,
        alt: 'MPUM 原图，展示模态投影、解剖分割与临床研究',
        previewAlt: 'MPUM 论文图 1 局部，展示 MR、PET 与 CT 影像及对应的分割结果',
        fullCaption: 'MPUM 框架与临床研究，论文图 1。',
        credit: { label: 'Chen 等，Nature Communications', href: 'https://www.nature.com/articles/s41467-025-64469-w' },
        license: { label: 'CC BY-NC-ND 4.0', href: 'https://creativecommons.org/licenses/by-nc-nd/4.0/' },
      },
      {
        id: 'pcnet',
        title: 'PCNet：用解剖类别关系指导 CT 分割',
        name: 'PCNet',
        venue: 'IEEE TMI，2024',
        summary: '利用器官、骨骼和肌肉之间的关系指导 CT 分割，在论文实验中提升了分割性能。',
        links: [
          { label: '论文', href: 'https://doi.org/10.1109/TMI.2024.3395349' },
          { label: '代码', href: 'https://github.com/YixinChen-AI/PCNet' },
        ],
        image: 'assets/img/research/pcnet-hierarchy.png',
        width: 1788, height: 998, dark: true,
        alt: 'PCNet 解剖层级图，展示功能系统与器官、血管、肌肉、骨骼的关系',
        previewAlt: 'PCNet 解剖层级图的中央部分，展示器官、血管、肌肉和骨骼的类别关系',
        fullCaption: 'PCNet 使用的解剖类别层级。',
        credit: { label: 'PCNet 官方代码库原图', href: 'https://github.com/YixinChen-AI/PCNet' },
      },
      {
        id: 'masld',
        title: '脂肪肝的多器官 PET/CT 影像变化',
        name: 'MASLD 全身 PET/CT 研究',
        venue: 'EJNMMI，2026 已接收',
        summary: '在两中心 294 位受试者中，16 项影像特征在 MASLD 与对照组间存在差异，并在第二中心复现。',
        links: [
          { label: '论文条目', href: '#publication-masld' },
        ],
        image: 'assets/img/research/masld-petct.png',
        width: 1753, height: 1253,
        alt: 'MASLD 研究原图，展示 PET/CT、多器官分割与器官定量测量',
        previewAlt: 'MASLD 接收稿图 2 局部，展示全身分割结果和器官类别',
        fullCaption: 'PET/CT 与多器官分割，接收稿图 2。',
        credit: { label: '陈亦新、周传志、郭丽娟等' },
      },
    ],
  },
};
