export const research = {
  en: {
    heading: 'Selected research',
    figureLink: 'View full figure',
    roleLabel: 'My contribution',
    works: [
      {
        id: 'mpum',
        title: 'One segmentation model for CT, MRI and PET',
        name: 'MPUM',
        venue: 'Nature Communications, 2025',
        authorship: 'First author',
        paragraphs: [
          'MPUM uses one model to segment anatomy in CT, MRI and PET. It shares what these scans have in common and adapts to each imaging modality.',
          'Trained on scans from 861 subjects, it achieved the highest Dice scores among the compared methods across the evaluated segmentation benchmarks. The study also tested haemorrhage localisation and brain–body metabolic analysis.',
        ],
        role: 'Study conception, experimental design, code implementation and manuscript drafting.',
        links: [
          { label: 'Paper', href: 'https://www.nature.com/articles/s41467-025-64469-w' },
          { label: 'Code', href: 'https://github.com/YixinChen-AI/MPUM' },
        ],
        image: 'assets/img/research/mpum-overview.png',
        width: 2000, height: 1811,
        alt: 'MPUM overview showing modality-specific kernels, anatomical segmentation and clinical analyses',
        previewAlt: 'Detail of MPUM Figure 1 showing segmentation examples and brain haemorrhage localisation',
        caption: 'Segmentation and diagnosis examples from Figure 1. Open the full original figure.',
        fullCaption: 'MPUM framework and clinical studies, Figure 1.',
        credit: { label: 'Chen et al., Nature Communications', href: 'https://www.nature.com/articles/s41467-025-64469-w' },
        license: { label: 'CC BY-NC-ND 4.0', href: 'https://creativecommons.org/licenses/by-nc-nd/4.0/' },
      },
      {
        id: 'pcnet',
        title: 'Anatomical relationships for CT segmentation',
        name: 'PCNet',
        venue: 'IEEE TMI, 2024',
        authorship: 'First author',
        paragraphs: [
          'PCNet uses relationships between organs, bones, muscles and other structures to guide CT segmentation.',
          'In the paper’s experiments, this approach improved CT segmentation and transferred to multiple downstream tasks.',
        ],
        role: 'First author; developed and evaluated the anatomy-guided segmentation method.',
        links: [
          { label: 'Paper', href: 'https://doi.org/10.1109/TMI.2024.3395349' },
          { label: 'Code', href: 'https://github.com/YixinChen-AI/PCNet' },
        ],
        image: 'assets/img/research/pcnet-hierarchy.png',
        width: 1788, height: 998, dark: true,
        alt: 'PCNet anatomical hierarchy linking functional systems with organs, vessels, muscles and bones',
        previewAlt: 'Central part of the PCNet anatomical hierarchy, with organs, vessels, muscles and bones',
        caption: 'Detail of the anatomical hierarchy used in PCNet. Open the full original diagram.',
        fullCaption: 'The anatomical hierarchy used in PCNet.',
        credit: { label: 'Original diagram from the PCNet repository', href: 'https://github.com/YixinChen-AI/PCNet' },
      },
      {
        id: 'masld',
        title: 'Multi-organ changes in fatty liver disease',
        name: 'Whole-body PET/CT in MASLD',
        venue: 'EJNMMI, accepted 2026',
        authorship: 'First author',
        paragraphs: [
          'We studied metabolic dysfunction-associated steatotic liver disease (MASLD) using PET/CT from 294 adults at two centres. Automated segmentation supported measurements of PET uptake, CT attenuation and tissue volume across organs.',
          'Sixteen imaging features differed between MASLD and controls and were replicated at the second centre, spanning the heart, upper-abdominal organs, fat, vessels and muscle.',
        ],
        role: 'Analytic approach, formal analyses, visualisation and manuscript drafting; contributed to study conception.',
        links: [
          { label: 'Publication entry', href: '#publication-masld' },
        ],
        image: 'assets/img/research/masld-petct.png',
        width: 1753, height: 1253,
        alt: 'MASLD study figure showing PET/CT examples, multi-organ segmentation and organ-level measurements',
        previewAlt: 'Detail of MASLD Figure 2 showing whole-body segmentation and organ groups',
        caption: 'Multi-organ segmentation from Figure 2 of the accepted manuscript. Open the full original figure.',
        fullCaption: 'PET/CT and multi-organ segmentation, Figure 2 of the accepted manuscript.',
        credit: { label: 'Chen, Zhou, Guo et al.' },
      },
    ],
  },
  zh: {
    heading: '代表研究',
    figureLink: '查看完整原图',
    roleLabel: '我的贡献',
    works: [
      {
        id: 'mpum',
        title: '一个模型分割 CT、MRI 与 PET',
        name: 'MPUM',
        venue: 'Nature Communications，2025',
        authorship: '第一作者',
        paragraphs: [
          'MPUM 用同一个模型分割 CT、MRI 和 PET 影像，在共享解剖知识的同时适应不同影像模态。',
          '模型使用 861 位受试者的数据训练。在论文评估的分割任务中，它的 Dice 评分高于所比较的方法。研究还测试了脑出血定位和脑与身体的代谢分析。',
        ],
        role: '研究构思、实验设计、代码实现和论文初稿撰写。',
        links: [
          { label: '论文', href: 'https://www.nature.com/articles/s41467-025-64469-w' },
          { label: '代码', href: 'https://github.com/YixinChen-AI/MPUM' },
        ],
        image: 'assets/img/research/mpum-overview.png',
        width: 2000, height: 1811,
        alt: 'MPUM 原图，展示模态投影、解剖分割与临床研究',
        previewAlt: 'MPUM 论文图 1 局部，展示 CT、MRI、PET 分割及脑出血定位',
        caption: '论文图 1 中的分割和诊断示例，点击可查看完整原图。',
        fullCaption: 'MPUM 框架与临床研究，论文图 1。',
        credit: { label: 'Chen 等，Nature Communications', href: 'https://www.nature.com/articles/s41467-025-64469-w' },
        license: { label: 'CC BY-NC-ND 4.0', href: 'https://creativecommons.org/licenses/by-nc-nd/4.0/' },
      },
      {
        id: 'pcnet',
        title: '用解剖类别关系指导 CT 分割',
        name: 'PCNet',
        venue: 'IEEE TMI，2024',
        authorship: '第一作者',
        paragraphs: [
          'PCNet 利用器官、骨骼、肌肉等解剖结构之间的关系，指导 CT 影像分割。',
          '在论文实验中，这种方法提升了 CT 分割性能，并能迁移到多项下游任务。',
        ],
        role: '作为第一作者，开发并评估了这一解剖关系引导的分割方法。',
        links: [
          { label: '论文', href: 'https://doi.org/10.1109/TMI.2024.3395349' },
          { label: '代码', href: 'https://github.com/YixinChen-AI/PCNet' },
        ],
        image: 'assets/img/research/pcnet-hierarchy.png',
        width: 1788, height: 998, dark: true,
        alt: 'PCNet 解剖层级图，展示功能系统与器官、血管、肌肉、骨骼的关系',
        previewAlt: 'PCNet 解剖层级图的中央部分，展示器官、血管、肌肉和骨骼类别',
        caption: 'PCNet 解剖类别层级局部，点击可查看完整原图。',
        fullCaption: 'PCNet 使用的解剖类别层级。',
        credit: { label: 'PCNet 官方代码库原图', href: 'https://github.com/YixinChen-AI/PCNet' },
      },
      {
        id: 'masld',
        title: '脂肪肝的多器官影像变化',
        name: 'MASLD 全身 PET/CT 研究',
        venue: 'EJNMMI，2026 已接收',
        authorship: '第一作者',
        paragraphs: [
          '利用两中心 294 位受试者的 PET/CT，研究代谢功能障碍相关脂肪性肝病（MASLD）。通过自动分割，测量多器官的 PET 摄取、CT 衰减和组织体积。',
          '16 项影像特征在 MASLD 与对照组间存在差异，并在第二中心复现，涉及心脏、上腹部器官、脂肪、血管和肌肉。',
        ],
        role: '分析方法、统计分析、可视化和论文初稿撰写，并参与研究构思。',
        links: [
          { label: '论文条目', href: '#publication-masld' },
        ],
        image: 'assets/img/research/masld-petct.png',
        width: 1753, height: 1253,
        alt: 'MASLD 研究原图，展示 PET/CT、多器官分割与器官定量测量',
        previewAlt: 'MASLD 接收稿图 2 局部，展示全身分割结果和器官类别',
        caption: '接收稿图 2 中的多器官分割，点击可查看完整原图。',
        fullCaption: 'PET/CT 与多器官分割，接收稿图 2。',
        credit: { label: '陈亦新、周传志、郭丽娟等' },
      },
    ],
  },
};
