export const research = {
  en: {
    heading: 'Selected research',
    figureLink: 'View full figure',
    roleLabel: 'My contribution',
    works: [
      {
        id: 'mpum',
        title: 'One segmentation model for CT, MRI and PET',
        name: 'MPUM',
        venue: 'Nature Communications, 2025',
        authorship: 'Co-first author',
        paragraphs: [
          'MPUM shares anatomical knowledge across CT, MRI and PET, while adapting its convolutional kernels to each imaging modality.',
          'We trained the model with data from 861 subjects. Clinical studies examined anatomical localisation of brain haemorrhage and brain–body metabolic associations in paediatric epilepsy.',
        ],
        role: 'Study conception, experimental design, code implementation and manuscript drafting.',
        links: [
          { label: 'Paper', href: 'https://www.nature.com/articles/s41467-025-64469-w' },
          { label: 'Code', href: 'https://github.com/YixinChen-AI/MPUM' },
        ],
        image: 'assets/img/research/mpum-overview.png',
        width: 2000, height: 1811,
        alt: 'MPUM overview showing modality-specific kernels, anatomical segmentation and clinical analyses',
        caption: 'MPUM framework and clinical studies. Original Figure 1.',
        credit: { label: 'Chen et al., Nature Communications', href: 'https://www.nature.com/articles/s41467-025-64469-w' },
        license: { label: 'CC BY-NC-ND 4.0', href: 'https://creativecommons.org/licenses/by-nc-nd/4.0/' },
      },
      {
        id: 'pcnet',
        title: 'Anatomical relationships for CT segmentation',
        name: 'PCNet',
        venue: 'IEEE TMI, 2024',
        authorship: 'First author',
        paragraphs: [
          'PCNet uses relationships between anatomical categories to guide multi-organ CT segmentation. Category prompts and hierarchical consistency constraints connect functional systems, organs and individual structures.',
          'The paper evaluates universal segmentation and transfer to downstream segmentation tasks.',
        ],
        links: [
          { label: 'Paper', href: 'https://doi.org/10.1109/TMI.2024.3395349' },
          { label: 'Code', href: 'https://github.com/YixinChen-AI/PCNet' },
        ],
        image: 'assets/img/research/pcnet-hierarchy.png',
        width: 1788, height: 998, dark: true,
        alt: 'PCNet anatomical hierarchy linking functional systems with organs, vessels, muscles and bones',
        caption: 'The anatomical hierarchy used in PCNet.',
        credit: { label: 'Original diagram from the PCNet repository', href: 'https://github.com/YixinChen-AI/PCNet' },
      },
      {
        id: 'masld',
        title: 'Multi-organ changes in fatty liver disease',
        name: 'Whole-body PET/CT in MASLD',
        venue: 'EJNMMI, accepted 2026',
        authorship: 'Co-first author',
        paragraphs: [
          'We studied metabolic dysfunction-associated steatotic liver disease (MASLD) using PET/CT from 294 adults at two centres. Automated segmentation supported measurements of PET uptake, CT attenuation and tissue volume across organs.',
          'Sixteen imaging features differed between MASLD and controls and were replicated at the second centre, spanning the heart, upper-abdominal organs, fat, vessels and muscle.',
        ],
        role: 'Analytic approach, formal analyses, visualisation and manuscript drafting; contributed to study conception.',
        links: [
          { label: 'Publication entry', href: '#publication-masld' },
        ],
        image: 'assets/img/research/masld-petct.png',
        width: 1753, height: 1253,
        alt: 'MASLD study figure showing PET/CT examples, multi-organ segmentation and organ-level measurements',
        caption: 'PET/CT, automated segmentation and organ-level quantification. Figure 2 from the accepted manuscript.',
        credit: { label: 'Chen, Zhou, Guo et al.' },
      },
    ],
  },
  zh: {
    heading: '代表研究',
    figureLink: '查看完整原图',
    roleLabel: '我的贡献',
    works: [
      {
        id: 'mpum',
        title: '一个模型分割 CT、MRI 与 PET',
        name: 'MPUM',
        venue: 'Nature Communications，2025',
        authorship: '共同第一作者',
        paragraphs: [
          'MPUM 在 CT、MRI 和 PET 之间共享解剖知识，并根据影像模态调整卷积核，让同一个模型适应不同的影像特征。',
          '模型使用 861 位受试者的数据训练。临床研究分别考察了脑出血的解剖定位，以及儿童癫痫中的脑与身体代谢关联。',
        ],
        role: '研究构思、实验设计、代码实现和论文初稿撰写。',
        links: [
          { label: '论文', href: 'https://www.nature.com/articles/s41467-025-64469-w' },
          { label: '代码', href: 'https://github.com/YixinChen-AI/MPUM' },
        ],
        image: 'assets/img/research/mpum-overview.png',
        width: 2000, height: 1811,
        alt: 'MPUM 原图，展示模态投影、解剖分割与临床研究',
        caption: 'MPUM 框架与临床研究，论文原图 1。',
        credit: { label: 'Chen 等，Nature Communications', href: 'https://www.nature.com/articles/s41467-025-64469-w' },
        license: { label: 'CC BY-NC-ND 4.0', href: 'https://creativecommons.org/licenses/by-nc-nd/4.0/' },
      },
      {
        id: 'pcnet',
        title: '用解剖类别关系指导 CT 分割',
        name: 'PCNet',
        venue: 'IEEE TMI，2024',
        authorship: '第一作者',
        paragraphs: [
          'PCNet 将解剖结构之间的类别关系用于多器官 CT 分割。通过类别提示和层级一致性约束，把功能系统、器官和具体结构联系起来。',
          '论文评估了通用分割性能，以及模型在下游分割任务中的迁移表现。',
        ],
        links: [
          { label: '论文', href: 'https://doi.org/10.1109/TMI.2024.3395349' },
          { label: '代码', href: 'https://github.com/YixinChen-AI/PCNet' },
        ],
        image: 'assets/img/research/pcnet-hierarchy.png',
        width: 1788, height: 998, dark: true,
        alt: 'PCNet 解剖层级图，展示功能系统与器官、血管、肌肉、骨骼的关系',
        caption: 'PCNet 使用的解剖类别层级。',
        credit: { label: 'PCNet 官方代码库原图', href: 'https://github.com/YixinChen-AI/PCNet' },
      },
      {
        id: 'masld',
        title: '脂肪肝的多器官影像变化',
        name: 'MASLD 全身 PET/CT 研究',
        venue: 'EJNMMI，2026 已接收',
        authorship: '共同第一作者',
        paragraphs: [
          '利用两中心 294 位受试者的 PET/CT，研究代谢功能障碍相关脂肪性肝病（MASLD）。通过自动分割，测量多器官的 PET 摄取、CT 衰减和组织体积。',
          '16 项影像特征在 MASLD 与对照组间存在差异，并在第二中心复现，涉及心脏、上腹部器官、脂肪、血管和肌肉。',
        ],
        role: '分析方法、统计分析、可视化和论文初稿撰写，并参与研究构思。',
        links: [
          { label: '论文条目', href: '#publication-masld' },
        ],
        image: 'assets/img/research/masld-petct.png',
        width: 1753, height: 1253,
        alt: 'MASLD 研究原图，展示 PET/CT、多器官分割与器官定量测量',
        caption: 'PET/CT、自动分割与器官定量测量，接收稿原图 2。',
        credit: { label: '陈亦新、周传志、郭丽娟等' },
      },
    ],
  },
};
